export interface Gaisei {
    id: string;
    kubun: string;
    systemName: string;
    gaiyo: string;
    shukanKashitsu: string;
    sekinin_Shozoku: string;
    sekinin_Name: string;
    renraku_Shozoku: string;
    renraku_Name: string;
    renraku_Naisen: string;
    unyoKaishi: string;
    jikiKoukai: string;
    user_Center: string;
    user_Kyoku: string;
    user_Seifu: string;
    user_Localgovernment: string;
    user_Ippan: string;
    system_Coope: string;
    kibo_Cnt: string;
    kibo_PV: string;
    infoType_Kimitsu3: string;
    infoType_Kimitsu2: string;
    infoType_Kanzen2: string;
    infoType_Kayo2: string;
    toriatsukaiseigen: string;
    kojin_Toriatsukai: string;
    kojin_Tokutei: string;
    systemType: string;
    dev_Way: string;
    dev_Other: string;
    app_LOC: string;
    app_GamenCnt: string;
    app_ChohyoCnt: string;
    server_BaseCnt: string;
    server_BackupCnt: string;
    server_Cnt: string;
    lineType_IE: string;
    lineType_SeifuNW: string;
    lineType_SINET: string;
    lineType_LGWIN: string;
    lineType_Other: string;
    packageName: string;
    packageDev: string;
    cloudService_UserUmu: string;
    cloudService_SeviceName: string;
    cloudService_Jigyosha: string;
    cloudService_ServiceKigyo: string;
    cloudService_Gaiyo: string;
    cloudService_Start: string;
    cloudService_End: string;
    cloudService_DomainName: string;
    cloudService_Kimitsu3: string;
    cloudService_Kimitsu2: string;
    cloudService_Kanzen2: string;
    cloudService_Kayo2: string;
    cloudService_Toriatsukai: string;
    cloudService_Schedule: string;
    mokuhyoRate: string;
    donyu_Jigyosha: string;
    donyu_Jiki: string;
    donyu_Price: string;
    hoshu_Jigyosha: string;
    hoshu_Start: string;
    hoshu_End: string;
    hoshu_Price: string;
    hoshu_SameDonyu: string;
    unyo_Jigyosha: string;
    unyo_Start: string;
    unyo_End: string;
    unyo_Price: string;
    unyo_SameDonyu: string;
    unyo_SameHoshu: string;
    isDelete: boolean;
}

export class GaiseiSystem implements Gaisei {

    id: string = '';
    kubun: string = '';
    systemName: string = '';
    gaiyo: string = '';
    shukanKashitsu: string = '';
    sekinin_Shozoku: string = '';
    sekinin_Name: string = '';
    renraku_Shozoku: string = '';
    renraku_Name: string = '';
    renraku_Naisen: string = '';
    unyoKaishi: string = '';
    jikiKoukai: string = '';
    user_Center: string = '';
    user_Kyoku: string = '';
    user_Seifu: string = '';
    user_Localgovernment: string = '';
    user_Ippan: string = '';
    system_Coope: string = '';
    kibo_Cnt: string = '';
    kibo_PV: string = '';
    infoType_Kimitsu3: string = '';
    infoType_Kimitsu2: string = '';
    infoType_Kanzen2: string = '';
    infoType_Kayo2: string = '';
    toriatsukaiseigen: string = '';
    kojin_Toriatsukai: string = '';
    kojin_Tokutei: string = '';
    systemType: string = '';
    dev_Way: string = '';
    dev_Other: string = '';
    app_LOC: string = '';
    app_GamenCnt: string = '';
    app_ChohyoCnt: string = '';
    server_BaseCnt: string = '';
    server_BackupCnt: string = '';
    server_Cnt: string = '';
    lineType_IE: string = '';
    lineType_SeifuNW: string = '';
    lineType_SINET: string = '';
    lineType_LGWIN: string = '';
    lineType_Other: string = '';
    packageName: string = '';
    packageDev: string = '';
    cloudService_UserUmu: string = '';
    cloudService_SeviceName: string = '';
    cloudService_Jigyosha: string = '';
    cloudService_ServiceKigyo: string = '';
    cloudService_Gaiyo: string = '';
    cloudService_Start: string = '';
    cloudService_End: string = '';
    cloudService_DomainName: string = '';
    cloudService_Kimitsu3: string = '';
    cloudService_Kimitsu2: string = '';
    cloudService_Kanzen2: string = '';
    cloudService_Kayo2: string = '';
    cloudService_Toriatsukai: string = '';
    cloudService_Schedule: string = '';
    mokuhyoRate: string = '';
    donyu_Jigyosha: string = '';
    donyu_Jiki: string = '';
    donyu_Price: string = '';
    hoshu_Jigyosha: string = '';
    hoshu_Start: string = '';
    hoshu_End: string = '';
    hoshu_Price: string = '';
    hoshu_SameDonyu: string = '';
    unyo_Jigyosha: string = '';
    unyo_Start: string = '';
    unyo_End: string = '';
    unyo_Price: string = '';
    unyo_SameDonyu: string = '';
    unyo_SameHoshu: string = '';
    isDelete: boolean = false;

}
